name: Docker Buildx CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
        with:
          install: true
          buildkitd-flags: --debug
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: mk-nginx:latest
          outputs: type=docker,dest=/tmp/mk-nginx.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mk-nginx
          path: /tmp/mk-nginx.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          buildkitd-flags: --debug
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mk-nginx
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/mk-nginx.tar
          docker image ls -a
